#	"$Name:  $";
#	"$Header:  $";
#=============================================================================
#
# file :        TangoDataServer.py
#
# description : Python source for the TangoDataServer and its commands. 
#                The class is derived from Device. It represents the
#                CORBA servant object which will be accessed from the
#                network. All commands which can be executed on the
#                TangoDataServer are implemented in this file.
#
# project :     TANGO Device Server
#
# $Author:  $
#
# $Revision:  $
#
# $Log:  $
#
# copyleft :    European Synchrotron Radiation Facility
#               BP 220, Grenoble 38043
#               FRANCE
#
#=============================================================================
#  		This file is generated by POGO
#	(Program Obviously used to Generate tango Object)
#
#         (c) - Software Engineering Group - ESRF
#=============================================================================
#


import PyTango
import sys

from TangoDataWriter import TangoDataWriter as TDW

#==================================================================
#   TangoDataServer Class Description:
#
#         Tango Server to store data in H5 files
#
#==================================================================


class TangoDataServer(PyTango.Device_4Impl):

#--------- Add you global variables here --------------------------

#------------------------------------------------------------------
#	Device constructor
#------------------------------------------------------------------
	def __init__(self,cl, name):
		PyTango.Device_4Impl.__init__(self,cl,name)
		TangoDataServer.init_device(self)
		self.tdw=TDW("name")
#------------------------------------------------------------------
#	Device destructor
#------------------------------------------------------------------
	def delete_device(self):
		print "[Device delete_device method] for device",self.get_name()


#------------------------------------------------------------------
#	Device initialization
#------------------------------------------------------------------
	def init_device(self):
		print "In ", self.get_name(), "::init_device()"
		self.set_state(PyTango.DevState.ON)
		self.get_device_properties(self.get_device_class())

#------------------------------------------------------------------
#	Always excuted hook method
#------------------------------------------------------------------
	def always_executed_hook(self):
		print "In ", self.get_name(), "::always_excuted_hook()"

#==================================================================
#
#	TangoDataServer read/write attribute methods
#
#==================================================================
#------------------------------------------------------------------
#	Read Attribute Hardware
#------------------------------------------------------------------
	def read_attr_hardware(self,data):
		print "In ", self.get_name(), "::read_attr_hardware()"



#------------------------------------------------------------------
#	Read TheXMLSettings attribute
#------------------------------------------------------------------
	def read_TheXMLSettings(self, attr):
		print "In ", self.get_name(), "::read_TheXMLSettings()"
		
		#	Add your own code here
 		
		attr.set_value(self.tdw.getXML())


#------------------------------------------------------------------
#	Write TheXMLSettings attribute
#------------------------------------------------------------------
	def write_TheXMLSettings(self, attr):
		print "In ", self.get_name(), "::write_TheXMLSettings()"
		data=[]
		attr.get_write_value(data)
		print "Attribute value = ", data
		self.tdw.setXML(data[0])
#	Add your own code here


#------------------------------------------------------------------
#	Read TheJSONRecord attribute
#------------------------------------------------------------------
	def read_TheJSONRecord(self, attr):
		print "In ", self.get_name(), "::read_TheJSONRecord()"
		
		#	Add your own code here
		
		attr.set_value(self.tdw.getJSON())


#------------------------------------------------------------------
#	Write TheJSONRecord attribute
#------------------------------------------------------------------
	def write_TheJSONRecord(self, attr):
		print "In ", self.get_name(), "::write_TheJSONRecord()"
		data=[]
		attr.get_write_value(data)
		print "Attribute value = ", data
		self.tdw.setJSON(data[0])

		#	Add your own code here



#==================================================================
#
#	TangoDataServer command methods
#
#==================================================================

#------------------------------------------------------------------
#	Record command:
#
#	Description: Record setting for one step
#                
#------------------------------------------------------------------
	def Record(self):
		print "In ", self.get_name(), "::Record()"
		#	Add your own code here
		self.tdw.record()


#------------------------------------------------------------------
#	Open command:
#
#	Description: Open the H5 file
#                
#------------------------------------------------------------------
	def Open(self):
		print "In ", self.get_name(), "::Open()"
		#	Add your own code here
		self.tdw.open()


#------------------------------------------------------------------
#	Close command:
#
#	Description: Close the H5 file
#                
#------------------------------------------------------------------
	def Close(self):
		print "In ", self.get_name(), "::Close()"
		#	Add your own code here
		self.tdw.close()


#==================================================================
#
#	TangoDataServerClass class definition
#
#==================================================================
class TangoDataServerClass(PyTango.DeviceClass):

	#	Class Properties
	class_property_list = {
		}


	#	Device Properties
	device_property_list = {
		}


	#	Command definitions
	cmd_list = {
		'Record':
			[[PyTango.DevVoid, ""],
			[PyTango.DevVoid, ""]],
		'Open':
			[[PyTango.DevVoid, ""],
			[PyTango.DevVoid, ""]],
		'Close':
			[[PyTango.DevVoid, ""],
			[PyTango.DevVoid, ""]],
		}


	#	Attribute definitions
	attr_list = {
		'TheXMLSettings':
			[[PyTango.DevString,
			PyTango.SCALAR,
			PyTango.READ_WRITE]],
		'TheJSONRecord':
			[[PyTango.DevString,
			PyTango.SCALAR,
			PyTango.READ_WRITE]],
		}


#------------------------------------------------------------------
#	TangoDataServerClass Constructor
#------------------------------------------------------------------
	def __init__(self, name):
		PyTango.DeviceClass.__init__(self, name)
		self.set_type(name);
		print "In TangoDataServerClass  constructor"

#==================================================================
#
#	TangoDataServer class main method
#
#==================================================================
if __name__ == '__main__':
	try:
		py = PyTango.Util(sys.argv)
		py.add_TgClass(TangoDataServerClass,TangoDataServer,'TangoDataServer')

		U = PyTango.Util.instance()
		U.server_init()
		U.server_run()

	except PyTango.DevFailed,e:
		print '-------> Received a DevFailed exception:',e
	except Exception,e:
		print '-------> An unforeseen exception occured....',e
