#	"$Name:  $";
#	"$Header:  $";
#=============================================================================
#
# file :        TangoDataServer.py
#
# description : Python source for the TangoDataServer and its commands. 
#                The class is derived from Device. It represents the
#                CORBA servant object which will be accessed from the
#                network. All commands which can be executed on the
#                TangoDataServer are implemented in this file.
#
# project :     TANGO Device Server
#
# $Author:  $
#
# $Revision:  $
#
# $Log:  $
#
# copyleft :    European Synchrotron Radiation Facility
#               BP 220, Grenoble 38043
#               FRANCE
#
#=============================================================================
#  		This file is generated by POGO
#	(Program Obviously used to Generate tango Object)
#
#         (c) - Software Engineering Group - ESRF
#=============================================================================
#


import PyTango
import sys

from TangoDataWriter import TangoDataWriter as TDW

#==================================================================
#   TangoDataServer Class Description:
#
#         Tango Server to store data in H5 files
#
#==================================================================
# 	Device States Description:
#
#   DevState.ON :       NeXuS Data Server is switch on
#   DevState.OFF :      NeXuS Data Writer is switch off
#   DevState.OPEN :     H5 file is open
#   DevState.INIT :     XML configuration is initialzed
#   DevState.RUNNING :  NeXus Data Server is writting
#==================================================================


class TangoDataServer(PyTango.Device_4Impl):

#--------- Add you global variables here --------------------------

#------------------------------------------------------------------
#	Device constructor
#------------------------------------------------------------------
	def __init__(self,cl, name):
		PyTango.Device_4Impl.__init__(self,cl,name)
		TangoDataServer.init_device(self)
		self.tdw=TDW("name.h5")

#------------------------------------------------------------------
#	Device destructor
#------------------------------------------------------------------
	def delete_device(self):
		print "[Device delete_device method] for device",self.get_name()
		self.set_state(PyTango.DevState.OFF)


#------------------------------------------------------------------
#	Device initialization
#------------------------------------------------------------------
	def init_device(self):
		print "In ", self.get_name(), "::init_device()"
		self.set_state(PyTango.DevState.ON)
		self.get_device_properties(self.get_device_class())

#------------------------------------------------------------------
#	Always excuted hook method
#------------------------------------------------------------------
	def always_executed_hook(self):
		print "In ", self.get_name(), "::always_excuted_hook()"

#==================================================================
#
#	TangoDataServer read/write attribute methods
#
#==================================================================
#------------------------------------------------------------------
#	Read Attribute Hardware
#------------------------------------------------------------------
	def read_attr_hardware(self,data):
		print "In ", self.get_name(), "::read_attr_hardware()"



#------------------------------------------------------------------
#	Read TheXMLSettings attribute
#------------------------------------------------------------------
	def read_TheXMLSettings(self, attr):
		print "In ", self.get_name(), "::read_TheXMLSettings()"
		
		#	Add your own code here
 		
		attr.set_value(self.tdw.getXML())


#------------------------------------------------------------------
#	Write TheXMLSettings attribute
#------------------------------------------------------------------
	def write_TheXMLSettings(self, attr):
		print "In ", self.get_name(), "::write_TheXMLSettings()"
		data=[]
		attr.get_write_value(data)
		print "Attribute value = ", data
		self.tdw.setXML(data[0])
		self.set_state(PyTango.DevState.INIT)


#---- TheXMLSettings attribute State Machine -----------------
	def is_TheXMLSettings_allowed(self, req_type):
		if self.get_state() in [PyTango.DevState.OFF,
		                        PyTango.DevState.OPEN,
		                        PyTango.DevState.RUNNING]:
			#	End of Generated Code
			#	Re-Start of Generated Code
			return False
		return True


#------------------------------------------------------------------
#	Read TheJSONRecord attribute
#------------------------------------------------------------------
	def read_TheJSONRecord(self, attr):
		print "In ", self.get_name(), "::read_TheJSONRecord()"
		
		#	Add your own code here
		
		attr.set_value(self.tdw.getJSON())


#------------------------------------------------------------------
#	Write TheJSONRecord attribute
#------------------------------------------------------------------
	def write_TheJSONRecord(self, attr):
		print "In ", self.get_name(), "::write_TheJSONRecord()"
		data=[]
		attr.get_write_value(data)
		print "Attribute value = ", data
		self.tdw.setJSON(data[0])

		#	Add your own code here


#---- TheJSONRecord attribute State Machine -----------------
	def is_TheJSONRecord_allowed(self, req_type):
		if self.get_state() in [PyTango.DevState.OFF,
		                        PyTango.DevState.RUNNING]:
			#	End of Generated Code
			#	Re-Start of Generated Code
			return False
		return True


#------------------------------------------------------------------
#	Read FileName attribute
#------------------------------------------------------------------
	def read_FileName(self, attr):
		print "In ", self.get_name(), "::read_FileName()"
		
		#	Add your own code here
		
		attr.set_value(self.tdw.fileName)


#------------------------------------------------------------------
#	Write FileName attribute
#------------------------------------------------------------------
	def write_FileName(self, attr):
		print "In ", self.get_name(), "::write_FileName()"
		data=[]
		attr.get_write_value(data)
		print "Attribute value = ", data
		self.tdw.fileName=data[0]

		#	Add your own code here


#---- FileName attribute State Machine -----------------
	def is_FileName_allowed(self, req_type):
		if self.get_state() in [PyTango.DevState.OFF,
		                        PyTango.DevState.OPEN,
		                        PyTango.DevState.RUNNING]:
			#	End of Generated Code
			#	Re-Start of Generated Code
			return False
		return True



#==================================================================
#
#	TangoDataServer command methods
#
#==================================================================

#------------------------------------------------------------------
#	Record command:
#
#	Description: Record setting for one step
#                
#------------------------------------------------------------------
	def Record(self):
		self.set_state(PyTango.DevState.RUNNING)
		print "In ", self.get_name(), "::Record()"
		#	Add your own code here
		self.tdw.record()
		self.set_state(PyTango.DevState.OPEN)


#---- Record command State Machine -----------------
	def is_Record_allowed(self):
		if self.get_state() in [PyTango.DevState.ON,
		                        PyTango.DevState.OFF,
		                        PyTango.DevState.INIT,
		                        PyTango.DevState.RUNNING]:
			#	End of Generated Code
			#	Re-Start of Generated Code
			return False
		return True


#------------------------------------------------------------------
#	Open command:
#
#	Description: Open the H5 file
#                
#------------------------------------------------------------------
	def Open(self):
		print "In ", self.get_name(), "::Open()"
		#	Add your own code here
		self.tdw.open()
		self.set_state(PyTango.DevState.OPEN)


#---- Open command State Machine -----------------
	def is_Open_allowed(self):
		if self.get_state() in [PyTango.DevState.ON,
		                        PyTango.DevState.OFF,
		                        PyTango.DevState.OPEN,
		                        PyTango.DevState.RUNNING]:
			#	End of Generated Code
			#	Re-Start of Generated Code
			return False
		return True


#------------------------------------------------------------------
#	Close command:
#
#	Description: Close the H5 file
#                
#------------------------------------------------------------------
	def Close(self):
		print "In ", self.get_name(), "::Close()"
		#	Add your own code here
		self.tdw.close()
		self.set_state(PyTango.DevState.INIT)


#---- Close command State Machine -----------------
	def is_Close_allowed(self):
		if self.get_state() in [PyTango.DevState.ON,
		                        PyTango.DevState.OFF,
		                        PyTango.DevState.INIT,
		                        PyTango.DevState.RUNNING]:
			#	End of Generated Code
			#	Re-Start of Generated Code
			return False
		return True


#==================================================================
#
#	TangoDataServerClass class definition
#
#==================================================================
class TangoDataServerClass(PyTango.DeviceClass):

	#	Class Properties
	class_property_list = {
		}


	#	Device Properties
	device_property_list = {
		}


	#	Command definitions
	cmd_list = {
		'Record':
			[[PyTango.DevVoid, ""],
			[PyTango.DevVoid, ""]],
		'Open':
			[[PyTango.DevVoid, ""],
			[PyTango.DevVoid, ""]],
		'Close':
			[[PyTango.DevVoid, ""],
			[PyTango.DevVoid, ""]],
		}


	#	Attribute definitions
	attr_list = {
		'TheXMLSettings':
			[[PyTango.DevString,
			PyTango.SCALAR,
			PyTango.READ_WRITE]],
		'TheJSONRecord':
			[[PyTango.DevString,
			PyTango.SCALAR,
			PyTango.READ_WRITE]],
		'FileName':
			[[PyTango.DevString,
			PyTango.SCALAR,
			PyTango.READ_WRITE]],
		}


#------------------------------------------------------------------
#	TangoDataServerClass Constructor
#------------------------------------------------------------------
	def __init__(self, name):
		PyTango.DeviceClass.__init__(self, name)
		self.set_type(name);
		print "In TangoDataServerClass  constructor"

#==================================================================
#
#	TangoDataServer class main method
#
#==================================================================
if __name__ == '__main__':
	try:
		py = PyTango.Util(sys.argv)
		py.add_TgClass(TangoDataServerClass,TangoDataServer,'TangoDataServer')

		U = PyTango.Util.instance()
		U.server_init()
		U.server_run()

	except PyTango.DevFailed,e:
		print '-------> Received a DevFailed exception:',e
	except Exception,e:
		print '-------> An unforeseen exception occured....',e
